import "./globals.css";
import { Inter, Poppins, Roboto } from "next/font/google";
import { Providers } from "./ReduxGlobal/provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] })
const poppins = Poppins({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
    <Providers>
        {children}
        </Providers>
      
      </body>
    </html>
  );
}
